# See: https://s.apache.org/asfyaml

# publishing the site uses the asf-site branch publish/staging block

staging:
  whoami: asf-site
  # this will generate infrastructure-template.staged.apache.org
  profile: template 

